set arraysize 1
set verify off

--Desenvolvimento 
DEFINE INSTANCE = ACXD
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = AFID
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = CCSD
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = CD9D
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = CDBD
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = CI9D
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = CR9D
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = DD9D
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = EISD
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = ICMD
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = IDBD
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = INTD
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = PDBD
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = RICD
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = RISD
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF

--Aceite
DEFINE INSTANCE = ACXA
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = AFIA
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = ARSA
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = CCSA
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = CD9A
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = CDBA
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = CORA
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = CR9A
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = DD9A
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = EISA
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = IDBA
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = INTA
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = PDBA
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = RICA
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = RISA
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = SNEA
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = SPKA
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = TMSA
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = UPAA
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF

--Filial
DEFINE INSTANCE = BH1P
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = DCXP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = IMGP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = NITP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = PA1P
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = RJ3P
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = RJOP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = SD1P
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = SXVP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = TIJP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF

--Integraçao Sudameris 
DEFINE INSTANCE = ASMI
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = INTI
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = RTSI
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = TMSI
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF

--Produção 
DEFINE INSTANCE = ACXP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = AFIP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = AMLP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = APOIO
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = ARSP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = ASMP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = BI2P
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = BIBP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = BIEP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = BKDP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = BOCP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = BOP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = CCIP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = CDBP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = CRPP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = DBAI
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = DBAP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = DBCP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = EBZP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = EXBH
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = FCOP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = GLSP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = GOLP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = HRMP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = HVTP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = ICCP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = IDBP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = LECP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = NWKP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = NWSP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = OEMP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = OWBP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = PC2P
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = PCCP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = PDBP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = PITP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = RCAP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = RECP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = RH9P
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = RI2P
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = RIBH
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = RIBP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = RICP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = RISP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = SEGP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = SJ9P
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = SMAP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = SVCP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = TDBP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = TMSP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = UPAP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
DEFINE INSTANCE = WWWP
CONN SYSTEM/USESYSTEM&INSTANCE@&INSTANCE
SPOOL C:\TEMP\&INSTANCE
@ABNDBA.SQL
SPOOL OFF
 
