--
-- Create Schema Script 
--   Database Version   :  9.2.0.5 
--   TOAD Version       : 8.0.0.47 
--   DB Connect String  : AMLP 
--   Schema             : BUSINESS 
--   Script Created by  : TTCN212 
--   Script Created at  : 04/03/05 20:26:29 
--   Physical Location  :  
--   Notes              :  
--

-- Object Counts: 
--   Indexes: 405       Columns: 770        
-- 

spool bitmap.log
select to_char(sysdate,'dd/mm/yyyy hh24:mi:ss') inicio from dual ;



CREATE BITMAP INDEX BO_TRXN_PRDCT_IDX ON BACK_OFFICE_TRXN
(MANTAS_TRXN_PRDCT_CD)
  local   nologging
PARALLEL ( DEGREE 2 INSTANCES 1 );


CREATE BITMAP INDEX CUST_JRDCN_CD ON CUST
(JRSDCN_CD)
  local   nologging
NOPARALLEL;


CREATE BITMAP INDEX EMP_JRDCN_IDX ON EMP
(JRSDCN_CD)
  local   nologging
PARALLEL ( DEGREE 2 INSTANCES 1 );


CREATE BITMAP INDEX EXCTN_JRDCN_CD ON EXECUTION
(JRSDCN_CD)
  local   nologging
PARALLEL ( DEGREE 2 INSTANCES 1 );

CREATE BITMAP INDEX EXCTN_CUST_TYP_CD ON EXECUTION
(CUST_TYPE_CD)
  local   nologging
PARALLEL ( DEGREE 2 INSTANCES 1 );


CREATE BITMAP INDEX EXCTN_EV_TYPE_IDX ON EXECUTION
(LAST_EVENT_TYPE_CD)
  local   nologging
PARALLEL ( DEGREE 2 INSTANCES 1 );


CREATE BITMAP INDEX EX_TRDR_ACCT_IDX ON EXECUTION
(TRDR_ACCT_TYPE_CD)
  local   nologging
PARALLEL ( DEGREE 2 INSTANCES 1 );



CREATE BITMAP INDEX INSTR_INS_TYPE_IDX ON INSTRUCTION
(INSTR_TYPE_CD)
  local   nologging
PARALLEL ( DEGREE 2 INSTANCES 1 );


CREATE BITMAP INDEX NTCPTRY_ACCTID_IDX ON NTCPTRY_PRFL
(PRFL_METRIC_CD, ACCT_INTRL_ID)
  local   nologging
PARALLEL ( DEGREE 2 INSTANCES 1 );


CREATE BITMAP INDEX ORDR_JRDCN_CD ON ORDR
(JRSDCN_CD)
  local   nologging
PARALLEL ( DEGREE 2 INSTANCES 1 );


CREATE BITMAP INDEX ORDR_BSACCT_TY_IDX ON ORDR
(BUYER_SELLR_ACCT_TYPE_CD)
  local   nologging
PARALLEL ( DEGREE 2 INSTANCES 1 );


CREATE BITMAP INDEX ORDR_TYPE_CD_IDX ON ORDR
(LAST_ORDR_TYPE_CD)
  local   nologging
PARALLEL ( DEGREE 2 INSTANCES 1 );


CREATE BITMAP INDEX SCRTY_JRDCN_CD ON SCRTY
(JRSDCN_CD)
  local   nologging
PARALLEL ( DEGREE 2 INSTANCES 1 );


CREATE BITMAP INDEX SCRTY_CRNCY_CD ON SCRTY
(ISSUE_CNTRY_CD)
  local   nologging
PARALLEL ( DEGREE 2 INSTANCES 1 );


CREATE BITMAP INDEX TRADE_JRDCN_CD ON TRADE
(JRSDCN_CD)
  local   nologging
PARALLEL ( DEGREE 2 INSTANCES 1 );


CREATE BITMAP INDEX TRADE_CUST_TYP_IDX ON TRADE
(CUST_TYPE_CD)
  local   nologging
PARALLEL ( DEGREE 2 INSTANCES 1 );


CREATE BITMAP INDEX TRADE_EV_TYPE_IDX ON TRADE
(LAST_EVENT_TYPE_CD)
  local   nologging
PARALLEL ( DEGREE 2 INSTANCES 1 );


CREATE BITMAP INDEX TRD_TRDR_ACCT_IDX ON TRADE
(TRDR_ACCT_TYPE_CD)
  local   nologging
PARALLEL ( DEGREE 2 INSTANCES 1 );

CREATE BITMAP INDEX ACCT_HOLDR_TYP_IDX ON ACCT
(MANTAS_ACCT_HOLDR_TYPE_CD)
  local   nologging
PARALLEL ( DEGREE 2 INSTANCES 1 );


CREATE BITMAP INDEX ACCT_BUS_TYPE_IDX ON ACCT
(MANTAS_ACCT_BUS_TYPE_CD)
  local   nologging
PARALLEL ( DEGREE 2 INSTANCES 1 );


CREATE BITMAP INDEX ACCT_JRDCN_IDX ON ACCT
(JRSDCN_CD) 
  local   nologging
PARALLEL ( DEGREE 2 INSTANCES 1 );

CREATE BITMAP INDEX ACCT_TYPE1_CD_IDX ON ACCT
(ACCT_TYPE1_CD)
  local   nologging
PARALLEL ( DEGREE 2 INSTANCES 1 );


select to_char(sysdate,'dd/mm/yyyy hh24:mi:ss') fim from dual ;

exit
