spool cria_dba_users.log
CREATE USER ABNOPER IDENTIFIED BY VALUES '61BB60F79602FAEC'
DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMPORARY
PROFILE DEFAULT;

GRANT SYSOPER TO ABNOPER;

-- Alessandra
CREATE USER F130290 IDENTIFIED BY F130290
DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMPORARY
PROFILE DEFAULT;

GRANT DBA TO F130290;

ALTER USER F130290 DEFAULT ROLE DBA;

GRANT SYSDBA TO F130290;

--AUDIT ALL, ALTER SEQUENCE, ALTER TABLE, COMMENT TABLE, DELETE TABLE, EXECUTE PROCEDURE, GRANT PROCEDURE,
--      GRANT TABLE, INSERT TABLE, LOCK TABLE, SELECT SEQUENCE, UPDATE TABLE
--BY F130290 BY ACCESS;

-- Mario
CREATE USER F203858 IDENTIFIED BY F203858
DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMPORARY
PROFILE DEFAULT;

GRANT DBA TO F203858;

ALTER USER F203858 DEFAULT ROLE DBA;

GRANT SYSDBA TO F203858;

--AUDIT ALL, ALTER SEQUENCE, ALTER TABLE, COMMENT TABLE, DELETE TABLE, EXECUTE PROCEDURE, GRANT PROCEDURE,
--      GRANT TABLE, INSERT TABLE, LOCK TABLE, SELECT SEQUENCE, UPDATE TABLE
--BY F203858 BY ACCESS;

-- Ricardo
CREATE USER F267627 IDENTIFIED BY F267627
DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMPORARY
PROFILE DEFAULT;

GRANT DBA TO F267627;

ALTER USER F267627 DEFAULT ROLE DBA;

GRANT SYSDBA TO F267627;

--AUDIT ALL, ALTER SEQUENCE, ALTER TABLE, COMMENT TABLE, DELETE TABLE, EXECUTE PROCEDURE, GRANT PROCEDURE,
--      GRANT TABLE, INSERT TABLE, LOCK TABLE, SELECT SEQUENCE, UPDATE TABLE
--BY F267627 BY ACCESS;

-- Andreia
CREATE USER F321982 IDENTIFIED BY F321982
DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMPORARY
PROFILE DEFAULT;

GRANT DBA TO F321982;

ALTER USER F321982 DEFAULT ROLE DBA;

GRANT SYSDBA TO F321982;

--AUDIT ALL, ALTER SEQUENCE, ALTER TABLE, COMMENT TABLE, DELETE TABLE, EXECUTE PROCEDURE, GRANT PROCEDURE,
--      GRANT TABLE, INSERT TABLE, LOCK TABLE, SELECT SEQUENCE, UPDATE TABLE
--BY F321982 BY ACCESS;

-- Claudio
CREATE USER F416444 IDENTIFIED BY F416444
DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMPORARY
PROFILE DEFAULT;

GRANT DBA TO F416444;

ALTER USER F416444 DEFAULT ROLE DBA;

GRANT SYSDBA TO F416444;

--AUDIT ALL, ALTER SEQUENCE, ALTER TABLE, COMMENT TABLE, DELETE TABLE, EXECUTE PROCEDURE, GRANT PROCEDURE,
--      GRANT TABLE, INSERT TABLE, LOCK TABLE, SELECT SEQUENCE, UPDATE TABLE
--BY F416444 BY ACCESS;

-- Garcia
CREATE USER F579211 IDENTIFIED BY F579211
DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMPORARY
PROFILE DEFAULT;

GRANT DBA TO F579211;

ALTER USER F579211 DEFAULT ROLE DBA;

GRANT SYSDBA TO F579211;

--AUDIT ALL, ALTER SEQUENCE, ALTER TABLE, COMMENT TABLE, DELETE TABLE, EXECUTE PROCEDURE, GRANT PROCEDURE,
--      GRANT TABLE, INSERT TABLE, LOCK TABLE, SELECT SEQUENCE, UPDATE TABLE
--BY F579211 BY ACCESS;

-- Edgar
CREATE USER F958069 IDENTIFIED BY F958069
DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMPORARY
PROFILE DEFAULT;

GRANT DBA TO F958069;

ALTER USER F958069 DEFAULT ROLE DBA;

GRANT SYSDBA TO F958069;

--AUDIT ALL, ALTER SEQUENCE, ALTER TABLE, COMMENT TABLE, DELETE TABLE, EXECUTE PROCEDURE, GRANT PROCEDURE,
--      GRANT TABLE, INSERT TABLE, LOCK TABLE, SELECT SEQUENCE, UPDATE TABLE
--BY F958069 BY ACCESS;

-- Orlando
CREATE USER TDEL224 IDENTIFIED BY TDEL224
DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMPORARY
PROFILE DEFAULT;

GRANT DBA TO TDEL224;

ALTER USER TDEL224 DEFAULT ROLE DBA;

GRANT SYSDBA TO TDEL224;

--AUDIT ALL, ALTER SEQUENCE, ALTER TABLE, COMMENT TABLE, DELETE TABLE, EXECUTE PROCEDURE, GRANT PROCEDURE,
--      GRANT TABLE, INSERT TABLE, LOCK TABLE, SELECT SEQUENCE, UPDATE TABLE
--BY TDEL224 BY ACCESS;

-- Ribeiro
CREATE USER TTCN203 IDENTIFIED BY TTCN203
DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMPORARY
PROFILE DEFAULT;

GRANT DBA TO TTCN203;

ALTER USER TTCN203 DEFAULT ROLE DBA;

GRANT SYSDBA TO TTCN203;

--AUDIT ALL, ALTER SEQUENCE, ALTER TABLE, COMMENT TABLE, DELETE TABLE, EXECUTE PROCEDURE, GRANT PROCEDURE,
--      GRANT TABLE, INSERT TABLE, LOCK TABLE, SELECT SEQUENCE, UPDATE TABLE
--BY TTCN203 BY ACCESS;

-- Gaui
CREATE USER TTCN204 IDENTIFIED BY TTCN204
DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMPORARY
PROFILE DEFAULT;

GRANT DBA TO TTCN204;

ALTER USER TTCN204 DEFAULT ROLE DBA;

GRANT SYSDBA TO TTCN204;

--AUDIT ALL, ALTER SEQUENCE, ALTER TABLE, COMMENT TABLE, DELETE TABLE, EXECUTE PROCEDURE, GRANT PROCEDURE,
--      GRANT TABLE, INSERT TABLE, LOCK TABLE, SELECT SEQUENCE, UPDATE TABLE
--BY TTCN204 BY ACCESS;

-- Daniel
CREATE USER TTCN207 IDENTIFIED BY TTCN207
DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMPORARY
PROFILE DEFAULT;

GRANT DBA TO TTCN207;

ALTER USER TTCN207 DEFAULT ROLE DBA;

GRANT SYSDBA TO TTCN207;

--AUDIT ALL, ALTER SEQUENCE, ALTER TABLE, COMMENT TABLE, DELETE TABLE, EXECUTE PROCEDURE, GRANT PROCEDURE,
--      GRANT TABLE, INSERT TABLE, LOCK TABLE, SELECT SEQUENCE, UPDATE TABLE
--BY TTCN207 BY ACCESS;

-- Odécio
CREATE USER TTCN212 IDENTIFIED BY TTCN212
DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMPORARY
PROFILE DEFAULT;

GRANT DBA TO TTCN212;

ALTER USER TTCN212 DEFAULT ROLE DBA;

GRANT SYSDBA TO TTCN212;

--AUDIT ALL, ALTER SEQUENCE, ALTER TABLE, COMMENT TABLE, DELETE TABLE, EXECUTE PROCEDURE, GRANT PROCEDURE,
--      GRANT TABLE, INSERT TABLE, LOCK TABLE, SELECT SEQUENCE, UPDATE TABLE
--BY TTCN212 BY ACCESS;

SELECT *
FROM V$PWFILE_USERS
ORDER BY 1;

SELECT DISTINCT USER_NAME
FROM DBA_STMT_AUDIT_OPTS
ORDER BY 1;

SELECT *
FROM DBA_ROLE_PRIVS
WHERE GRANTEE IN 
('F130290',
'F203858',
'F267627',
'F321982',
'F416444',
'F579211',
'F958069',
'TDEL224',
'TTCN203',
'TTCN204',
'TTCN207',
'TTCN212');
spool off
prompt
prompt Ed cria_dba_users	@cria_dba_users
prompt
