conn ttcn212@dbap
SELECT TO_CHAR(DBSS_DT_COLLECT,'YYYY-Mm') sequencia, TO_CHAR(DBSS_DT_COLLECT,'YYYY-Mon') DATA, SUM(DBSS_VL_SEGMENT_SIZE) bytes 
FROM dbamon.DBA_DB_SEGMENT_SIZE
WHERE DBSS_DBIN_CD_SID = 'AMLP'
GROUP BY TO_CHAR(DBSS_DT_COLLECT,'YYYY-Mm'), TO_CHAR(DBSS_DT_COLLECT,'YYYY-Mon')
ORDER BY 1
