CREATE TABLE TESTE_CONTA (
NR_SEQ_PESSOA             NUMBER(6),
NR_SEQ_CTACONTAB          NUMBER(6),
NR_CTACONTAB              VARCHAR2(30 byte),
DS_CTACONTAB              VARCHAR2(50 byte),
NR_SEQ_CTACONTAB_PAI      NUMBER(6),
DS_DET_CTACONTAB          VARCHAR2(1000 byte),
    	CONSTRAINT R_550_1 FOREIGN KEY(NR_SEQ_PESSOA, NR_SEQ_CTACONTAB_PAI)
    		REFERENCES TESTE_CONTA(NR_SEQ_PESSOA, NR_SEQ_CTACONTAB), 
    	CONSTRAINT XAK1CONTAS_CONTABEIS_1 UNIQUE(NR_SEQ_PESSOA, NR_CTACONTAB)
    		USING INDEX	TABLESPACE USER_DATA 
    		STORAGE ( INITIAL 256K NEXT 0K MINEXTENTS 1 MAXEXTENTS 
    		2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    		PCTFREE 10 INITRANS 2 MAXTRANS 255, 
    	CONSTRAINT XAK2CONTAS_CONTABEIS_1 UNIQUE(NR_SEQ_PESSOA, NR_SEQ_CTACONTAB_PAI,	DS_CTACONTAB) 
    		USING INDEX	TABLESPACE USER_DATA 
	    	STORAGE ( INITIAL 256K NEXT 0K MINEXTENTS 1 MAXEXTENTS 
    		2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    		PCTFREE 10 INITRANS 2 MAXTRANS 255, 
    	CONSTRAINT XPKCONTAS_CONTABEIS_1 PRIMARY KEY(NR_SEQ_PESSOA, NR_SEQ_CTACONTAB))  
ORGANIZATION INDEX  
    TABLESPACE USER_DATA 
		PCTFREE 10 INITRANS 1 MAXTRANS 255 
    		STORAGE ( INITIAL 256K NEXT 0K MINEXTENTS 1 MAXEXTENTS 
    		2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING ;



INSERT INTO TESTE_CONTA  select NR_SEQ_PESSOA, NR_SEQ_CTACONTAB, NR_CTACONTAB, DS_CTACONTAB, NR_SEQ_CTACONTAB_PAI,
						DS_DET_CTACONTAB
					 from erp_tectraining.contas_contabeis;

COMMIT;


select 'insert into teste_conta (NR_SEQ_PESSOA,NR_SEQ_CTACONTAB,DS_CTACONTAB) '||chr(10)||
       ' values ('||NR_SEQ_PESSOA||','||NR_SEQ_CTACONTAB||','''||DS_CTACONTAB||''');'
    from teste_conta;

select NR_SEQ_CTACONTAB,DS_CTACONTAB from teste_conta;

select column_name, position, constraint_name
from dba_cons_columns
where table_name = 'TESTE_CONTA' and constraint_name like '%PK%';
