DROP MATERIALIZED VIEW ttcn212.ACCT_MV;

CREATE MATERIALIZED VIEW business.ACCT_MV 
TABLESPACE MANTAS_DATA
NOCACHE
LOGGING
NOPARALLEL
REFRESH FORCE ON DEMAND
AS 
(select * from business.acct where LAST_ACTVY_DT >
 (select CLNDR_DT from MANTAS.KDD_CAL where CLNDR_NM = 'SYSCAL' and CLNDR_DAY_AGE = 7));

CREATE UNIQUE INDEX business.PK_ACCT_MV ON business.ACCT_MV
(ACCT_INTRL_ID)
noLOGGING
TABLESPACE MANTAS_INDEX
PARALLEL ( DEGREE 4 INSTANCES 1 );

CREATE INDEX business.ACCTMV_CUST_IDX    ON business.ACCT_MV
(PRMRY_CUST_INTRL_ID)
noLOGGING
TABLESPACE MANTAS_INDEX
PARALLEL ( DEGREE 4 INSTANCES 1 );

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  ACCT_MV TO PUBLIC;

DROP PUBLIC SYNONYM ACCT_MV;

CREATE PUBLIC SYNONYM ACCT_MV FOR ACCT_MV;
