CREATE ROLE ERWIN;
GRANT SELECT ON DBA_DATA_FILES TO ERWIN;
GRANT SELECT ON DBA_SEGMENTS  TO ERWIN;
GRANT SELECT ON DBA_TABLESPACES TO ERWIN;
GRANT SELECT ON DBA_TEMP_FILES TO ERWIN;
GRANT SELECT ON DBA_ROLLBACK_SEGS TO ERWIN;

