Select
  Case When G_OWNER = 1 And G_SEGMENT_NAME = 1 And G_SEGMENT_TYPE = 1 And G_TABLESPACE_NAME = 1 Then 'TOTAL GERAL' Else OWNER End OWNER,
  Case When G_OWNER = 0 And G_SEGMENT_NAME = 1 And G_SEGMENT_TYPE = 1 And G_TABLESPACE_NAME = 0 Then 'TOTAL TABLESPACE' Else SEGMENT_NAME End SEGMENT_NAME,
  Case When G_OWNER = 0 And G_SEGMENT_NAME = 1 And G_SEGMENT_TYPE = 0 And G_TABLESPACE_NAME = 0 Then 'TOTAL SEGMENT_TYPE' Else SEGMENT_TYPE End SEGMENT_TYPE,  
  TABLESPACE_NAME,
  BYTES
From
   ( 
    Select
      Grouping(OWNER) G_OWNER,
      Grouping(SEGMENT_NAME) G_SEGMENT_NAME,
      Grouping(SEGMENT_TYPE) G_SEGMENT_TYPE,
      Grouping(TABLESPACE_NAME) G_TABLESPACE_NAME,  
      OWNER, 
      SEGMENT_NAME,
      SEGMENT_TYPE,
      TABLESPACE_NAME,
      Sum(BYTES) BYTES
    From 
     DBA_SEGMENTS
    Where 
     OWNER In ('GEDPROD','GEDSCS') --And TABLESPACE_NAME ='TBS_GEDSTS_DISTRIB'
    Group By  Cube(OWNER,SEGMENT_NAME,SEGMENT_TYPE,TABLESPACE_NAME) 
    Order By 
     TABLESPACE_NAME, 
     SEGMENT_TYPE,
     Grouping(TABLESPACE_NAME), Grouping(SEGMENT_NAME), Grouping(SEGMENT_TYPE)
    ) A
Where
  (G_OWNER = 0 And G_SEGMENT_NAME = 0 And G_SEGMENT_TYPE = 0 And G_TABLESPACE_NAME = 0) Or
  (G_OWNER = 0 And G_SEGMENT_NAME = 1 And G_SEGMENT_TYPE = 1 And G_TABLESPACE_NAME = 0) Or
  (G_OWNER = 0 And G_SEGMENT_NAME = 1 And G_SEGMENT_TYPE = 0 And G_TABLESPACE_NAME = 0) Or
  (G_TABLESPACE_NAME = 1 And G_SEGMENT_NAME = 1 And G_OWNER = 1 And G_SEGMENT_TYPE = 1)