--SELECT * FROM v$sql WHERE parsing_user_id = (SELECT USER_ID FROM dba_users WHERE username = 'INGEST_USER') ORDER BY LAST_LOAD_TIME DESC 
SELECT -- SQL_TEXT, SORTS, LOADED_VERSIONS, USERS_OPENING, 
	   FETCHES, EXECUTIONS, USERS_EXECUTING,
	    INVALIDATIONS 
		-- ,BUFFER_GETS, ROWS_PROCESSED, KEPT_VERSIONS, ELAPSED_TIME, CPU_TIME, ELAPSED_TIME - CPU_TIME "DELTA TIME" 
					 FROM v$sql WHERE sql_text='SELECT  /*+ ORDERED */ ACCT_SEQ_ID FROM BUSINESS.ACCT WHERE ACCT_INTRL_ID = :1'