Accept Tablespace prompt 'Entre com a Tablespace : '
COLUMN Bytes FORMAT 999G999G999G999
SELECT SUBSTR(TBS.NAME,1,30) TableSpace,
       SUBSTR(TAB.NAME,1,30) Tabela,
       DECODE(TAB.MAXIMUM_NUMBER_OF_ROWS,'0',1, NULL,1,TAB.MAXIMUM_NUMBER_OF_ROWS) *
       SUM(DECODE(COL.DATATYPE,'DATE',7,COL.MAXIMUM_LENGTH)) Bytes
  FROM CI_COLUMNS COL,
       CI_TABLE_DEFINITIONS TAB,
       CI_TABLESPACES TBS
 WHERE COL.TABLE_REFERENCE = TAB.ID AND
       TAB.APPLICATION_SYSTEM_OWNED_BY  = 81144 AND
       TAB.TABLESPACE_REFERENCE = TBS.ID AND
       TBS.APPLICATION_SYSTEM_OWNED_BY  = TAB.APPLICATION_SYSTEM_OWNED_BY AND
       TBS.NAME = UPPER('&Tablespace')
GROUP BY TBS.NAME, TAB.NAME, TAB.MAXIMUM_NUMBER_OF_ROWS
ORDER BY TableSpace DESC, Bytes DESC , TAB.NAME DESC
/

