set echo on
spool tsttmp3.log
drop  TABLESPACE TSTEMP99
/
set echo off
pause foi_?
set echo on
CREATE TEMPORARY TABLESPACE TSTEMP99
	    TEMPFILE '/ora/u84/oradata/prd3/tmp/TSTEMP99a.dbf' SIZE 6500M reuse AUTOEXTEND Off
		extent MANAGEMENT LOCAL 
/
ALTER TABLESPACE TSTEMP99
	ADD TEMPFILE '/ora/u85/oradata/prd3/tmp/tstemp99b.dbf' SIZE 6500M  reuse AUTOEXTEND Off
/ 
ALTER TABLESPACE TSTEMP99
	ADD TEMPFILE '/ora/u86/oradata/prd3/tmp/tstemp99c.dbf' SIZE 6500M  reuse AUTOEXTEND Off
/ 
set echo off
pause foi_?
set echo on

ALTER USER sys TEMPORARY TABLESPACE TSTEMP99;

ALTER USER system TEMPORARY TABLESPACE TSTEMP99;

ALTER USER AC01 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER FORN TEMPORARY TABLESPACE TSTEMP99;

ALTER USER PRDX99 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER SUP915 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER ADM TEMPORARY TABLESPACE TSTEMP99;

ALTER USER PROD TEMPORARY TABLESPACE TSTEMP99;

ALTER USER CONC TEMPORARY TABLESPACE TSTEMP99;

ALTER USER SEGR TEMPORARY TABLESPACE TSTEMP99;

ALTER USER OUTLN TEMPORARY TABLESPACE TSTEMP99;

ALTER USER VERITAS TEMPORARY TABLESPACE TSTEMP99;

ALTER USER GC10 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER MK08 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER CLIE TEMPORARY TABLESPACE TSTEMP99;

ALTER USER PROP TEMPORARY TABLESPACE TSTEMP99;

ALTER USER DM1 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER GCA5 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER SPOTUSER TEMPORARY TABLESPACE TSTEMP99;

ALTER USER PRPE TEMPORARY TABLESPACE TSTEMP99;

ALTER USER QUEST TEMPORARY TABLESPACE TSTEMP99;

ALTER USER DBSNMP TEMPORARY TABLESPACE TSTEMP99;

ALTER USER PESQ TEMPORARY TABLESPACE TSTEMP99;

ALTER USER PDPE TEMPORARY TABLESPACE TSTEMP99;

ALTER USER OEM0 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER GCA4 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER MK10 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER IPA2 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER FCHK TEMPORARY TABLESPACE TSTEMP99;

ALTER USER QUEST2 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER SOPS TEMPORARY TABLESPACE TSTEMP99;

ALTER USER GCTS TEMPORARY TABLESPACE TSTEMP99;

ALTER USER GR01 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER OEMUSER TEMPORARY TABLESPACE TSTEMP99;

ALTER USER GL01 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER LJ08 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER TE54 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER GCON TEMPORARY TABLESPACE TSTEMP99;

ALTER USER MK04 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER AC51 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER GCA7 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER GC51 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER AC34 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER AC31 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER TE51 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER GCA3 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER TI53 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER GL03 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER PTBD_OPER TEMPORARY TABLESPACE TSTEMP99;

ALTER USER SOX TEMPORARY TABLESPACE TSTEMP99;

ALTER USER TI54 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER SEGN TEMPORARY TABLESPACE TSTEMP99;

ALTER USER TI55 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER GCA8 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER PERFSTAT TEMPORARY TABLESPACE TSTEMP99;

ALTER USER QUEST9I TEMPORARY TABLESPACE TSTEMP99;

ALTER USER CRM5 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER TI56 TEMPORARY TABLESPACE TSTEMP99;

ALTER USER TI52 TEMPORARY TABLESPACE TSTEMP99;

set echo off
spool off
