
SELECT * FROM CLIENTES;

INSERT INTO CLIENTES
VALUES ('1471156710', 'Erica Carvalho', 'Rua Iriqutia', 'Jardins', 'Sao Paulo', 'SP', '80012212',
TO_DATE('1990-09-01','yyyy-mm-dd'), 27, 'F', 170000, 24500, 0);

SELECT * FROM TABELA_DE_CLIENTES

SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO AS DATA_NASCIMENTO,
IDADE, SEXO, LIMITE_DE_CREDITO AS LIMITE_CREDITO, VOLUME_DE_COMPRA AS VOLUME_COMPRA, PRIMEIRA_COMPRA
FROM TABELA_DE_CLIENTES;

INSERT INTO CLIENTES
SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO AS DATA_NASCIMENTO,
IDADE, SEXO, LIMITE_DE_CREDITO AS LIMITE_CREDITO, VOLUME_DE_COMPRA AS VOLUME_COMPRA, PRIMEIRA_COMPRA
FROM TABELA_DE_CLIENTES;

INSERT INTO CLIENTES
SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO AS DATA_NASCIMENTO,
IDADE, SEXO, LIMITE_DE_CREDITO AS LIMITE_CREDITO, VOLUME_DE_COMPRA AS VOLUME_COMPRA, PRIMEIRA_COMPRA
FROM TABELA_DE_CLIENTES WHERE CPF <> '1471156710'

SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO AS DATA_NASCIMENTO,
IDADE, SEXO, LIMITE_DE_CREDITO AS LIMITE_CREDITO, VOLUME_DE_COMPRA AS VOLUME_COMPRA, PRIMEIRA_COMPRA
FROM TABELA_DE_CLIENTES WHERE CPF NOT IN (SELECT CPF FROM CLIENTES);

INSERT INTO CLIENTES
SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO AS DATA_NASCIMENTO,
IDADE, SEXO, LIMITE_DE_CREDITO AS LIMITE_CREDITO, VOLUME_DE_COMPRA AS VOLUME_COMPRA, PRIMEIRA_COMPRA
FROM TABELA_DE_CLIENTES WHERE CPF NOT IN (SELECT CPF FROM CLIENTES);

DELETE FROM CLIENTES;

INSERT INTO CLIENTES
VALUES ('1471156710', 'Erica Carvalho', 'Rua Iriqutia', 'Jardins', 'Sao Paulo', 'SP', '80012212',
TO_DATE('1990-09-01','yyyy-mm-dd'), 27, 'F', 170000, 24500, 0);

INSERT INTO CLIENTES
VALUES ('3623344710', 'Marcos Nogueira', 'Av. Pastor Martin Luther King Junior', 'Inhauma', 
'Rio de Janeiro', 'RJ', '22002012',
TO_DATE('1995-01-13','yyyy-mm-dd'), 23, 'M', 110000, 22000, 1);

SELECT * FROM CLIENTES;

INSERT INTO CLIENTES
SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO AS DATA_NASCIMENTO,
IDADE, SEXO, LIMITE_DE_CREDITO AS LIMITE_CREDITO, VOLUME_DE_COMPRA AS VOLUME_COMPRA, PRIMEIRA_COMPRA
FROM TABELA_DE_CLIENTES WHERE CPF NOT IN (SELECT CPF FROM CLIENTES);




