
INSERT INTO PRODUTOS 
(CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES
('1040107','Light - 350 ml - Melancia', 'Melancia','350 ml', 'Lata', 4.56);

SELECT * FROM PRODUTOS;

INSERT INTO PRODUTOS 
(CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES
('1040108','Light - 350 ml - Graviola', 'Graviola','350 ml', 'Lata', 4.00);

INSERT INTO PRODUTOS 
VALUES
('1040109','Light - 350 ml - Acai', 'Acai','350 ml', 'Lata', 5.60);


INSERT ALL
INTO PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES ('1040110','Light - 350 ml - Jaca', 'Jaca','350 ml', 'Lata', 6.00)
INTO PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES('1040111','Light - 350 ml - Manga', 'Manga','350 ml', 'Lata', 3.50)
SELECT * FROM DUAL;

SELECT * FROM PRODUTOS;







